### ISSUE TITLE
reload without restart server

### ISSUE THREAD

**Issue by arthurtalkgoal** [bkeepers/dotenv#176]
hi i am using dotenv in my rails in unicorn.   

I wonder is there anyway to reload my dotenv without restarting unicorn

**Comment by bkeepers** [comment]
There is not. I'd be happy to accept a simple patch that adds support for it, but it's not something I intend to implement. Note that you can reload the values yourself by calling `Dotenv.overload("path/to/.env")` in your application's initialization process.

One of the reasons I don't advocate for using dotenv in production is because it loads the environment variables within the ruby process, which makes it very difficult to track which variables were previously set and which were loaded by dotenv. If you set these variables in the environment of your server (`/etc/environment`, `/etc/profile`, etc) then unicorn reloading will just work.

**Comment by justindowning** [comment]
@arthurtalkgoal Hello! I resolved this with [this change](https://github.com/bkeepers/dotenv/pull/61#issuecomment-31462380) to `config/unicorn.rb`.

**Comment by arthurtalkgoal** [comment]
Hi @justindowning , wow, that is smart!

**Comment by crice88** [comment]
@jdowning this saved my bacon!!
