### ISSUE TITLE
readme's advice to put gem at top of Gemfile is counterproductive

### ISSUE THREAD

**Issue by MaxPleaner** [bkeepers/dotenv#192]
My goal was to set an ENV variable in `.env` and read it in `rails console`. This didn't work when I put the gem at the top of my Gemfile, but did work when I put it at the bottom. I am using `gem 'dotenv-rails', :groups => [:development, :test]`, by the way. Perhaps the README should be changed, since it advises putting the gem at the top of the Gemfile.

**Comment by bkeepers** [comment]
I'm not able to duplicate any issues with ordering. Can you confirm that you are?

The advice to put it at the top of the gemfile is so that dotenv initializes and loads the environment before any other gems that may depend on it.

Let me know if you can duplicate the issue and I'll open this back up or update the docs.
