### ISSUE TITLE
Rake tasks in Rails always initialized in "development"

### ISSUE THREAD

**Issue by gerry3** [bkeepers/dotenv#219]
`rails 4.2.1`
`dotenv-rails 2.0.2`
`dotenv 2.0.2`

files: `.env.development` & `.env.test` with a subset of vars

`rake spec` has `.env.development` vars only. Again, my `.env.test` is a subset, so maybe new vars would be set too, but existing ones are not overwritten. In any case, I only want the `.env.test` config, so overwriting wouldn't solve the issue fully.

Not sure why #45 was closed. Am I missing something?

**Comment by jonnyarnold** [comment]
:+1:

**Comment by SRod86** [comment]
Having the same issue too. Anyone know a fix for this?

**Comment by leomao10** [comment]
Actually, I found that it will load `.env.test`, but because `.env.development` was already loaded before `.env.test`, and since `Dotenv.load` won't override the env var if it exist, it will use var defined in `.env.development` not `.env.test`.

The whole process is like this:

1. `rake spec` call Rakefile in root folder, which will 
  ```
  require File.expand_path('../config/application', __FILE__)
  ```
2. application will trigger [`before_configuration` hook defined by dotenv](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L20), which will load following 3 env files:

  - `.env.local`
  - `.env.development`
  - `.env`

3. spec rake task get call, and call this code in your spec:
  
  ```
  require 'rails_helper'
  ```

4. In rails_helper.rb, ENV['RAILS_ENV'] was set to 'test'.

5. Then, config/application.rb was required again by `config/environment`, and `before_configuration` hook was triggered, only now `Rails.env == 'test'`. Therefore, it will load following 3 files:

  - `.env.local`
  - `.env.test`
  - `.env`

But since `before_configuration`  hook is using `load`, it won't override existing value.

As a temporary solution, I add this line in my `rails_helper.rb`:
```
Dotenv.overload('.env.test')
```
To force dotenv override any value defined in `.env.development`

**Comment by gerry3** [comment]
@leomao10 `overload` doesn't fully fix my issue as I do not want any of the `.env.development` values loaded in test

**Comment by leomao10** [comment]
I see, in that case, dotenv need to be smart enough to ignore the first `before_configuration` hook. Maybe there is a better railie hook for this situation.

**Comment by bitherder** [comment]
Would something like this: https://github.com/bkeepers/dotenv/compare/master...bitherder:reset-to-original-env?expand=1
or even this: https://github.com/bkeepers/dotenv/compare/master...bitherder:reset-to-original-env-simpler?expand=1

**Comment by bkeepers** [comment]
Is everyone here using rspec? I just opened #241 which I'm guessing will "fix the glitch".

**Comment by bitherder** [comment]
Yes, the cases were we're having trouble are related to rspec

**Comment by skaes** [comment]
Actually, I think this should be fixed in rspec-rails.

**Comment by johnnadeau** [comment]
I have this issue with my application using  rspec & dotenv, but adding `Dotenv.overload('.env.test')` to my `rails_helper.rb` is *ok* for now in my application. 

I'm willing to help test a solution when you come to one, just let me know.

**Comment by martinstreicher** [comment]
Just a brief note to say the solution for this issue can be unexpected...

```
   def env
      @env ||= if defined?(Rake.application) && Rake.application.top_level_tasks.grep(TEST_RAKE_TASKS).any?
        env = Rake.application.options.show_tasks ? "development" : "test"
        ActiveSupport::EnvironmentInquirer.new(env)
      else
        ::Rails.env
      end
    end
    TEST_RAKE_TASKS = /^(default$|test(:|$)|parallel:spec|spec(:|$))/
```

In our case, we had (questionably, I'll admit) a task named `test:fixtures:generate` that expected to run in `development` mode per normal _rake_ task, but given its prefix and the code above, forced itself to run in `test` mode. Thus, _.env.test_ was preferred over _.env.local_ and the wrong `RAILS_MASTER_KEY` was loaded, causing the task to fail with a decryption error.

**Comment by bkeepers** [comment]
@martinstreicher I can see how that would be confusing. I'm open to ideas to resolve it.

**Comment by bkeepers** [comment]
I haven't had time to look into this yet, but is the `RAILS_ENV` environment variable set when running `rake test`? If not, one soution would be for dotenv to use `RAILS_ENV` if it's explicitly set, otherwise try to guess. Then, your rake task could do:

```ruby
task "test:fixtures:generate" do
  ENV["RAILS_ENV"] = "development"
  Rake::Task["environment"].invoke
  # … other stuff here …
end
```

Dotenv could even define `environment:test` and `environment:development` tasks that you could depend on to force an environment.

```ruby
task "test:fixtures:generate" => "environment:development" do
  # … other stuff here …
end
```

**Comment by martinstreicher** [comment]
I will look -- my recollection is setting the `RAILS_ENV` on the command-line did not affect the outcome. 

I understand the intent: if you run `rake`, you expect it to run the default task, `test`, and therefore setting the internal environment in doting to `test` makes sense. 

There is an opportunity for surprise and befuddlement though.
