### ISSUE TITLE
Overwrite existing environment variables

### ISSUE THREAD

**Issue by siegy22** [bkeepers/dotenv#278]
Hi there!

I ran into an issue when using a proxy on a production system (using passenger).
Somehow passenger evaluated the .bash_profile script when starting from `mod_apache`.

However, I noticed that existing ENV variables never get overwritten by dotenv. Why doesn't dotenv overwrite existing ENV variables? 

I am using `dotenv-rails, 2.1.0`. I saw that there's a method `apply!` on the `Environment` class, this is what I need, but I didn't find a doc how to use it :grin:

Cheers :beers:

**Comment by bkeepers** [comment]
Hey @siegy22. This is definitely intentional. Dotenv assumes the  deployment environment has more knowledge about configuration than the application does. You can call `Dotenv.overload` to overwrite existing environment variables.

I'll leave this open as a reminder to update the docs. If anyone wants to take a pass at it, be my guest!
