### ISSUE TITLE
rspec fix appears to break if used with web-console

### ISSUE THREAD

**Issue by samandmoore** [bkeepers/dotenv#289]
Hi,

I am working on a Rails 4.2 app and we've included the `web-console` gem in our `development` group.

After upgrading from dotenv-rails 2.1 to 2.2, we are now getting an error when we run `rake spec` or `bundle exec rake spec`. Using the `bin/rspec` or `bundle exec rspec` works fine. Also, using `RAILS_ENV=test bundle exec rake spec` works as intended.

The error:
```
$ bundle exec rake spec
Web Console is activated in the test environment. This is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false
```

the Gemfile looks something like this:

```ruby
group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'dotenv-rails'
end

group :development do
  gem 'web-console'
end
```

All that I can surmise is that `web-console` is being required (or initialized) after the environment has been set to `RAILS_ENV=test` due to this recent patch: https://github.com/bkeepers/dotenv/pull/241/files

I haven't had time to dig in much more, but I can verify that reverting to dotenv-rails 2.1 fixes this issue. That's a bummer for me though because I want a bunch of the fixes that have been added to dotenv in releasees since 2.1, like not loading `.env.local` in tests.

I'm not sure if `web-console` is the only gem that exhibits this incompatibility. But, it's a commonly used gem with Rails so I figured that you'd want to know about this issue.

Any help would be much appreciated.

*edited for clarity.

**Comment by siegy22** [comment]
@bkeepers I think we don't want to close this issue.. 🤔

**Comment by bkeepers** [comment]
@siegy22 ok, reopened.  I don't have time to dig into this, but will review PRs if someone wants to take a pass at fixing it.

**Comment by samandmoore** [comment]
Thanks for re-opening. I had been hoping to take a crack at fixing it, but I haven't been able to find the time.

**Comment by effron** [comment]
I did some more digging here, maybe i can shed some light as to what is happening. Or at least reiterate what @samandmoore said in a slightly different way.

Our workflow is to run `rake spec` without specifying a rails environment (which I think is a common workflow, it's why this exists https://github.com/rspec/rspec-rails/blob/v3.7.2/lib/generators/rspec/install/templates/spec/rails_helper.rb#L3).

The default rails `application.rb` contains a `Bundler.require` (https://github.com/rails/rails/blob/v5.0.7/railties/lib/rails/generators/rails/app/templates/config/application.rb#L21)

`application.rb` will run using the development environment, and `Bundler.require` will load all of the development gems.

Then, this will run https://github.com/bkeepers/dotenv/blob/v2.2.0/lib/dotenv/rails.rb#L13

Finally, the application will initialize, which invokes this code in web-console
https://github.com/rails/web-console/blob/v3.6.2/lib/web_console/railtie.rb#L16

causing the rake task to abort with this message, because the rails environment is now test
```
Web Console is activated in the test environment. This is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

If you still want to run it the test environment (and know
what you are doing), put this in your Rails application
configuration:

    config.web_console.development_only = false
```

So, it seems like web-console (or any other development gem that does not want to be initialized in test mode) will not work if the rails environment is set to test in between `Bundler.require` and application initialization.
