### ISSUE TITLE
rake task doesn't load `.env.test`

### ISSUE THREAD

**Issue by ValentinTrinque** [bkeepers/dotenv#302]
### Steps to reproduce

1. I started a fresh new Rails application using:

```
rails new . --api --database=postgresql
```

2. I inserted dotenv-rails into the Gemfile:

```ruby
group :development, :test do
  gem 'dotenv-rails'
end
```
3. I setup two environment file `.env.development` and `.env.test` with:

```
DATABASE_URL=postgres://val@localhost/myapp_dev
````

and

```
DATABASE_URL=postgres://val@localhost/myapp_test
````

respectively.

4. Run `rake db:create`.

### Expected behavior
I am expecting `rake db:create` to load `.env.test` environment variable as pointed by the README.

Example:
```
Created database 'myapp_dev'
Created database 'myapp_test'
```

### Actual behavior

But I get:

```
Created database 'myapp_dev'
ERROR:  database "myapp_dev" already exists
STATEMENT:  CREATE DATABASE "myapp_dev" ENCODING = 'unicode'
Database 'myapp_dev' already exists
```

As you can see, instead of creating the development and test database, it attempts to create the development database twice. Clearly,  dotenv is ignoring the `.env.test`.

### System configuration
**dotenv version**:
2.2.1

**Rails version**:
5.1.0

**Ruby version**:
2.4.1

**Comment by siegy22** [comment]
I think the problem is that rails won't switch environments between creating the databases.. this whole command is running in the development environment.

So to solve your issue you could use a `.env` file:

```
MYAPP_DEV_DATABASE=myapp_dev
MYAPP_TEST_DATABASE=myapp_test
```

**Comment by ValentinTrinque** [comment]
Yes, that is exactly how I did it. That's a shame, really :( We could have cleaner approach, by having the same environment key everywhere and just stubbing inside the environment which would drastically minimize the `if Rails.env.test?`...

**Comment by thisismydesign** [comment]
Is there really no solution to this?

Here's what's happening basically: https://github.com/rails/rails/blob/f507085fa2a7625324e6f4e3ecef9b27dabefb4f/activerecord/lib/active_record/tasks/database_tasks.rb#L339

One approach I could see is monkey patching [DatabaseConfig.configs_for](https://github.com/rails/rails/blob/f507085fa2a7625324e6f4e3ecef9b27dabefb4f/activerecord/lib/active_record/database_configurations.rb#L29) to reload envs. That's obviously bad but a hack in your Rakefile might still be better than having polluted production code. Any other ideas?

I'd argue to keep this issue open / mention it somewhere because it's causing headaches very often and this reference is hard to find.

**Comment by thisismydesign** [comment]
I created a gem that patches ActiveRecord to fix this issue: [dotenv_rails_db_tasks_fix](https://github.com/thisismydesign/dotenv_rails_db_tasks_fix/)
Also reported it to Rails: https://github.com/rails/rails/issues/32926

**Comment by thisismydesign** [comment]
..and wrote a blogpost detailing some of the possible solutions: https://medium.com/@csaba.apagyi/solving-rake-db-tasks-with-dotenv-executed-twice-in-dev-environment-4b1cb447d325
