### ISSUE TITLE
Is it possible to have loaded variables prefixed?

### ISSUE THREAD

**Issue by dachinat** [bkeepers/dotenv#331]
In my situation I need to load `.env` file from frontend, I need to get `PORT` from there for further redirects from Rails controllers to frontend.

When I'm loading that file in `application.rb`, Rails server starts at that port, which I really don't need.

Is it possible to have these loaded variables prefixed? For example if I have `PORT` in `.env`, can I make use of it as `CLIENT_PORT`?

Thanks for this gem.

**Comment by jonmagic** [comment]
Hi @dachinat, thank you for the question. Let me make sure I understand.

> In my situation I need to load .env file from frontend, I need to get PORT from there for further redirects from Rails controllers to frontend.

You have a .env that looks like this:

```
PORT=3000
```

> When I'm loading that file in application.rb

Are you using the dotenv-rails gem [like this](https://github.com/bkeepers/dotenv#rails) or the dotenv gem [like this](https://github.com/bkeepers/dotenv#sinatra-or-plain-ol-ruby)?

> Rails server starts at that port, which I really don't need.

Could you explain this a bit more?

> Is it possible to have these loaded variables prefixed? For example if I have PORT in .env, can I make use of it as CLIENT_PORT?

At this time now. But you could change the variable name in `.env` to be what you want or even duplicate it:

```
PORT=3000
CLIENT_PORT=3000
```

If I am understanding things correctly I'm guessing we would say no, we won't support programmatically adding prefixes. We would prefer explicitly setting the needed environment variables in `.env`.

**Comment by dachinat** [comment]
@jonmagic Thanks for your response.

I'm using `dotenv` (Sinatra or plain ol' Ruby)

To explain about Rails starting at that port is that if one for example runs `PORT=3001 rails s` server will listen on `3001`. So, when I was loading `PORT` variable from `client/.env` (CRA frontend) in `application.rb` like so

```
# Load environment variables from client directory
Dotenv.load(Rails.root.join('client', ".env#{Rails.env.production? ? '.production' : nil}"))
```

Rails was taking that loaded `PORT` into consideration when I was issuing `$ rails s` command. I just wanted to use that variable for redirection URLs.

Thanks for answering my question. I think I'll be taking a different approach to this problem then.

**Comment by jonmagic** [comment]
> CRA frontend

TIL CRA :smile: Which is funny because I've built two react apps over the last year, one with a rails backend and then one with a node backend but never saw that acronym.

This probably won't help but here are some ideas based on my experience. If you are using the rails webpacker gem to compile and serve the CRA frontend in dev then the port stuff should all be handled for you. If you are using weback-dev-server and you need to override redirects in rails the easy way is to write any redirects as full urls so that rails doesn't try to build them with it's own host and port. I also ran into an issue with omniauth that was fixed by using the full_host option where you can change the url that omniauth expects after the oauth redirect.

**Comment by dachinat** [comment]
Yes, I wanted to say Create-React-App 😃

Thanks for responding. I'll definitely take your recommendations into account.
