### ISSUE TITLE
[PROPOSAL] - Load order - Environment specific vs Global

### ISSUE THREAD

**Issue by MattiaMalonni** [bkeepers/dotenv#414]
So, this is the deal. In my Rails app, I have 3 environments (development, staging, production) with the following configuration:

| environment  | env file         |
|--------------|------------------|
| ** global ** | .env             |
|  development | .env.development |
| staging      | .env.staging     |
| production   | .env.production  |

Two of them (`development` and `staging`) share the same value for a specific environment variable:
```
FOO="bar"
```
The third (`production`) is using a different value:
```
FOO="baz"
```

As of today, I need to write the same variable in all three 'environment specific' files with the relative values, because they don't override the global `.env` file.

It wouldn't be better if the 'environment specific' file can be used first, and fallback to the global `.env` file, if needed?

With that, I can simply declare `FOO="bar"` in the `.env` and override the value in the `.env.production` file.

**Comment by pioneerskies** [comment]
Was searching for already opened issue about this matter. But what I was expecting was to find a filled bug, not a proposal, since reading this part of the docs https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use I understand that, e.g., `.env.local` should already override the `.env`.

Am i missing something?

I have a similar scenario where `.env` is the "template" committed in repo and `.env.local` is intended as the override, but instead I've to delete empty keys in `.env` since they are overrided.

Using dotenv-rails 2.7.5

**Comment by mattiamalonni** [comment]
!notstale
